### ISSUE TITLE
dateString parsing does not match resume-schema definition "optional" parts

### ISSUE THREAD

**Issue by cometsong** [rbardini/jsonresume-theme-even#21]
### Bug
Parsing of date format in `resume-schema` has all parts optional except only *year* required.

This is implemented as a `"definition"` in their repo's `schema.json`:
> https://github.com/jsonresume/resume-schema/blob/master/schema.json#L5

### Recreate
To recreate, remove the *month* and *day* from one of the `"work"` entries, run the `resumed render`, view the result showing "Jan"

**Comment by rbardini** [comment]
That's because the JavaScript `Date` object will default to the first day of the month or first month of the year, if they're not defined:

```js
const dateA = new Date('2023')
dateA.getFullYear() // 2023
dateA.getMonth() // 0 (month is 0-indexed)
dateA.getDate() // 1

const dateB = new Date('2023-06')
dateB.getFullYear() // 2023
dateB.getMonth() // 5
dateB.getDate() // 1
```

Thus, my recommendation is to _always define the month_, even though a monthless date is valid according to the schema.
