### ISSUE TITLE
markdown in skills?

### ISSUE THREAD

**Issue by jave** [rbardini/jsonresume-theme-even#23]
It doesnt seem possible to use markdown in skills?

I try to use formatting in skills as a kind of workaround, because I would like to enumerate at which workplace a skill was aquired, and I would like workplaces to stand out from the actual skills.

Ok, to make it somewhat clearer, I use a lisp syntax as frontend to jsonresume so it looks like this:

           {"name" "Machine Learning, Artificial Intelligence", "level" "",
            "keywords" [ "NVIDIA", "MLOps"]
            "wp" ["Jobtech Development"]}

then it gets transformed to json like this:

{
    "name" : "Machine Learning, Artificial Intelligence",
    "level" : "",
    "keywords" : [ "<b>Jobtech Development</b>", "NVIDIA", "MLOps" ]
  }

in this the transformer use the bold tag, but markdown wouldve been better if it worked.

**Comment by rbardini** [comment]
Markdown is only supported on paragraph-like fields such as `summary` and `description`, since the parser wraps single lines with `<p>` tags. It's probably best to continue using HTML in your case.

**Comment by jave** [comment]
ok tnx
