### ISSUE TITLE
Missing type in projects

### ISSUE THREAD

**Issue by felipecrs** [rbardini/jsonresume-theme-even#5]
Hi,

As per the schema:

```jsonc
"projects": [
  { 
    "type": // e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'
   }
]
```

This field does not seem to appear in the rendered theme.

**Comment by rbardini** [comment]
I'm not sure how to represent this. Right now we have:

https://github.com/rbardini/jsonresume-theme-even/blob/28d6f247d67e1e9f3ca4bf2a7514a9a09f4681c5/partials/projects.hbs#L15-L22

Any suggestions?

**Comment by felipecrs** [comment]
I also don't know... maybe if we could find a theme which already uses it but I doubt there is one.
