### ISSUE TITLE
Support for line breaks

### ISSUE THREAD

**Issue by arhohuttunen** [rbardini/jsonresume-theme-even#7]
Have you considered something like converting `\n` to `</p><p>` like the [flat theme did](https://github.com/erming/jsonresume-theme-flat/commit/ab927e90afd1b76323b4c423f2dca8f5cf76bb6a)?

**Comment by rbardini** [comment]
I did, but in the end decided not to support it as I didn't see widespread usage.

One thing I'm still considering is to render Markdown content in summaries. That would cover a myriad of possibilities, including multiple paragraphs.

**Comment by arhohuttunen** [comment]
Thanks for the information. Meanwhile I was thinking about customizing the theme with a paragraphifying register helper, but then I found out [this](https://github.com/jsonresume/resume-cli/issues/386), so it’s suddenly becoming a little bit involved.

**Comment by rbardini** [comment]
Just released v0.5.0 with Markdown support in section content—basically everywhere a paragraph used to be. This means paragraphs can be defined with blank lines (`\n\n`) separating them 🎉

This version is not yet installed with the latest resume-cli, but you can try it by installing separately.

**Comment by arhohuttunen** [comment]
Awesome, I’ll be sure to give it a try!
